version: '3.5'

services:
  trafz:
    image: traefik:v2.4.8
    ports:
      - target: 80
        published: 80
        mode: host
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    command:
      - --log.level=DEBUG # debug while we get it working, for more levels/info see https://docs.traefik.io/observability/logs/
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-web
      - --entrypoints.web.address=:80
      - --entrypoints.web-secured.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=web-secured # force HTTPS
      - --certificatesresolvers.mytlschallenge.acme.httpChallenge.entrypoint=web
      - --certificatesresolvers.mytlschallenge.acme.email=blue@aquarat.za.net
      - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
      - --serversTransport.insecureSkipVerify=true
    volumes:
      - /home/ubuntu/swarm/traefik:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-web

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=airnode
      - POSTGRES_USER=airnode
      - POSTGRES_DB=airnode
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  traefik-web:
    external: true

volumes:
  pg_data:
